apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-service-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game-service
      version: green
  template:
    metadata:
      labels:
        app: game-service
        version: green
    spec:
      containers:
        - name: game-service
          image: yasithw/game-service:latest
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DATABASE_URL
